version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-type: "all"
        versions: ["*"]
        target-branch: "develop" 
