version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"  
    ignore:
      - dependency-type: "all"
        versions: ["*"]
        target-branch: "master" 
