version: 2
updates:
  - package-ecosystem: "*"  # Update all ecosystems
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"   
# Exclude specific branches from updates
branches:
  ignore:
    - "master"