name: CodeQL Blocker

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check-codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get Pull Request ID
        id: get_pr_id
        run: echo ${{ github.event.pull_request.number }}

      - name: Get CodeQL Results
        id: get_codeql_results
        uses: octokit/rest@v18
        with:
          endpoints: getPullRequestCodeScanningAlerts
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          pull_number: ${{ steps.get_pr_id.outputs }}
          per_page: 100  # Adjust per_page limit if needed

      - name: Parse CodeQL Results
        run: |
          results=$(echo ${{ steps.get_codeql_results.outputs }})
          critical_count=$(echo $results | jq '.alerts | .[] | select(.severity == "critical") | . | length')
          high_count=$(echo $results | jq '.alerts | .[] | select(.severity == "high") | . | length')
          if [[ $critical_count -gt 0 || $high_count -gt 0 ]]; then
            echo "Found critical or high severity vulnerabilities!"
            exit 1
          fi

      - name: Fail Pull Request if Vulnerabilities Found
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Pull Request blocked due to critical or high severity CodeQL findings."
            })
        if: failure()
